### ISSUE TITLE
KEY.gpg not working

### ISSUE THREAD

**Issue by Stalkerfish** [ThePBone/PPA-Repository#1]
Thats the output of `sudo apt update` after adding the repo, using the key. (All the steps were followed strictly)

`W: Erro GPG: https://thepbone.github.io/Viper4Linux-GUI-PPA ./ InRelease: As seguintes assinaturas eram inválidas: EXPKEYSIG FB0D51CE457BCF7E Tim Schneeberger <thebone.main@gmail.com>`

`E: The repository 'https://thepbone.github.io/Viper4Linux-GUI-PPA ./ InRelease' is not signed.`

`N: Updating from such a repository can't be done securely, and is therefore disabled by default.`

`N: See apt-secure(8) manpage for repository creation and user configuration details.`

That way I can't install Viper, and I really love it

**Comment by timschneeb** [comment]
Should work again, I updated the PPA keys a few weeks ago.
